"""
Destination Service — single AI engine, in-memory cache, startup pre-warming.

Architecture:
- ALL content generated by Gemini (highlights, restaurants, transport, weather, news)
- No external APIs needed (OpenWeatherMap, NewsAPI removed) — simpler for demo
- In-memory cache keyed by (airport_code, language) for content, weather, news
- On API startup, pre-warms cache for configured destinations + languages
- First UI request hits cache → <50ms response instead of 20-30s
"""

from app.models.schemas import (
    DestinationContent, Destination, Highlight, Restaurant,
    AirportTransport, TransportOption, WeatherForecast, LocalNews,
    EmergencyContacts
)
from app.adapters.gemini_adapter import gemini_adapter
# NOTE: weather_adapter and news_adapter removed — Gemini generates everything now
# from app.adapters.weather_adapter import weather_adapter
# from app.adapters.news_adapter import news_adapter
from data.loaders.csv_loader import csv_loader
from typing import List, Dict, Tuple
import logging
import time

logger = logging.getLogger(__name__)


class DestinationService:
    """Service for destination content with in-memory caching"""

    def __init__(self):
        # Cache: (airport_code, language) → response
        self._content_cache: Dict[Tuple[str, str], DestinationContent] = {}
        self._weather_cache: Dict[Tuple[str, str], List[WeatherForecast]] = {}
        self._news_cache: Dict[Tuple[str, str], List[LocalNews]] = {}

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def get_destination_content(self, airport_code: str, language: str = "en") -> DestinationContent:
        """Get destination content — from cache if available, else generate"""
        cache_key = (airport_code, language)

        if cache_key in self._content_cache:
            logger.info(f"CACHE HIT: destination content {airport_code}/{language}")
            return self._content_cache[cache_key]

        logger.info(f"CACHE MISS: generating destination content {airport_code}/{language}")
        start = time.perf_counter()

        content = self._generate_content(airport_code, language)
        self._content_cache[cache_key] = content

        elapsed = round((time.perf_counter() - start) * 1000)
        logger.info(f"Destination content generated in {elapsed}ms — cached for next request")

        return content

    def get_weather(self, airport_code: str, language: str = "en") -> List[WeatherForecast]:
        """Get weather — from cache if available, else generate with Gemini"""
        cache_key = (airport_code, language)

        if cache_key in self._weather_cache:
            logger.info(f"CACHE HIT: weather {airport_code}/{language}")
            return self._weather_cache[cache_key]

        logger.info(f"CACHE MISS: generating weather {airport_code}/{language} via Gemini")
        start = time.perf_counter()

        dest_info = csv_loader.get_destination_info(airport_code)
        if not dest_info:
            raise ValueError(f"Destination not found: {airport_code}")

        city = dest_info["destination"].city

        try:
            weather_data = gemini_adapter.generate_weather(city, language)
            forecasts = [WeatherForecast(**w) for w in weather_data]
        except Exception as e:
            logger.error(f"Gemini weather failed: {e}, using fallback")
            forecasts = self._fallback_weather()

        self._weather_cache[cache_key] = forecasts

        elapsed = round((time.perf_counter() - start) * 1000)
        logger.info(f"Weather generated in {elapsed}ms — cached")

        return forecasts

    def get_news(self, airport_code: str, language: str = "en") -> List[LocalNews]:
        """Get news — from cache if available, else generate with Gemini"""
        cache_key = (airport_code, language)

        if cache_key in self._news_cache:
            logger.info(f"CACHE HIT: news {airport_code}/{language}")
            return self._news_cache[cache_key]

        logger.info(f"CACHE MISS: generating news {airport_code}/{language} via Gemini")
        start = time.perf_counter()

        news_items = self._generate_news(airport_code, language)
        self._news_cache[cache_key] = news_items

        elapsed = round((time.perf_counter() - start) * 1000)
        logger.info(f"News generated in {elapsed}ms — cached")

        return news_items

    # ------------------------------------------------------------------
    # Pre-warming (called from app startup)
    # ------------------------------------------------------------------

    def prewarm(self, airports: List[str], languages: List[str]) -> None:
        """Pre-generate and cache content for given airport+language combos.

        Called on API startup so the first UI request is instant.
        """
        total = len(airports) * len(languages)
        logger.info("")
        logger.info("╔═════════════════════════════════════════════════════════╗")
        logger.info("║  🔥  PRE-WARMING CACHE                                ║")
        logger.info("╠═════════════════════════════════════════════════════════╣")
        logger.info(f"║  {len(airports)} airport(s) × {len(languages)} language(s) = {total} combo(s){' ' * max(0, 37 - len(str(len(airports))) - len(str(len(languages))) - len(str(total)))}║")
        logger.info(f"║  Airports:  {', '.join(airports)}{' ' * max(0, 43 - len(', '.join(airports)))}║")
        logger.info(f"║  Languages: {', '.join(languages)}{' ' * max(0, 43 - len(', '.join(languages)))}║")
        logger.info("╚═════════════════════════════════════════════════════════╝")
        overall_start = time.perf_counter()

        combo_idx = 0
        for airport_code in airports:
            for language in languages:
                combo_idx += 1
                tag = f"{airport_code}/{language}"

                logger.info("")
                logger.info(f"┌─────────────────────────────────────────────────────")
                logger.info(f"│  [{combo_idx}/{total}]  ✈️  {tag}")
                logger.info(f"├─────────────────────────────────────────────────────")

                # ── Section 1: Destination Content ──
                logger.info(f"│")
                logger.info(f"│  📦  DESTINATION CONTENT")
                logger.info(f"│  ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄")
                try:
                    start = time.perf_counter()
                    self.get_destination_content(airport_code, language)
                    elapsed = round((time.perf_counter() - start) * 1000)
                    logger.info(f"│      🏛️  Highlights   ✅  ready")
                    logger.info(f"│      🍝  Restaurants  ✅  ready")
                    logger.info(f"│      🚇  Transport    ✅  ready")
                    logger.info(f"│      ⏱️  {elapsed}ms total")
                except Exception as e:
                    logger.error(f"│      ❌  Content failed: {e}")

                # ── Section 2: Weather ──
                logger.info(f"│")
                logger.info(f"│  🌤️  WEATHER FORECAST")
                logger.info(f"│  ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄")
                try:
                    start = time.perf_counter()
                    self.get_weather(airport_code, language)
                    elapsed = round((time.perf_counter() - start) * 1000)
                    logger.info(f"│      🌡️  3-day forecast ✅  ready")
                    logger.info(f"│      ⏱️  {elapsed}ms")
                except Exception as e:
                    logger.error(f"│      ❌  Weather failed: {e}")

                # ── Section 3: News ──
                logger.info(f"│")
                logger.info(f"│  📰  NEWS HEADLINES")
                logger.info(f"│  ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄")
                try:
                    start = time.perf_counter()
                    self.get_news(airport_code, language)
                    elapsed = round((time.perf_counter() - start) * 1000)
                    logger.info(f"│      📄  5 headlines   ✅  ready")
                    logger.info(f"│      ⏱️  {elapsed}ms")
                except Exception as e:
                    logger.error(f"│      ❌  News failed: {e}")

                logger.info(f"│")
                logger.info(f"└─────────────────────────────────────────────────────")

        total_elapsed = round((time.perf_counter() - overall_start) * 1000)
        cached = len(self._content_cache)
        logger.info("")
        logger.info("╔═════════════════════════════════════════════════════════╗")
        logger.info("║  🔥  PRE-WARM COMPLETE                                ║")
        logger.info(f"║  ✅  {cached} destination(s) cached in {total_elapsed/1000:.1f}s{' ' * max(0, 23 - len(str(cached)) - len(f'{total_elapsed/1000:.1f}'))}║")
        logger.info("╚═════════════════════════════════════════════════════════╝")
        logger.info("")

    # ------------------------------------------------------------------
    # Internal — content generation
    # ------------------------------------------------------------------

    def _generate_content(self, airport_code: str, language: str) -> DestinationContent:
        """Generate content with Gemini directly in the target language"""
        dest_info = csv_loader.get_destination_info(airport_code)
        if not dest_info:
            raise ValueError(f"Destination not found: {airport_code}")

        destination = dest_info["destination"]
        emergency_contacts = dest_info["emergency_contacts"]

        # Generate each piece with Gemini (with fallback)
        try:
            start = time.perf_counter()
            highlights_data = gemini_adapter.generate_highlights(
                destination.city, destination.country, language
            )
            highlights = [Highlight(**h) for h in highlights_data]
            elapsed = round((time.perf_counter() - start) * 1000)
            logger.info(f"│          🏛️  Highlights  → {len(highlights)} items  ({elapsed}ms)")
        except Exception as e:
            logger.error(f"│          🏛️  Highlights  → fallback  ({e})")
            highlights = self._fallback_highlights(destination.city)

        try:
            start = time.perf_counter()
            restaurants_data = gemini_adapter.generate_restaurants(
                destination.city, destination.country, language
            )
            restaurants = [Restaurant(**r) for r in restaurants_data]
            elapsed = round((time.perf_counter() - start) * 1000)
            logger.info(f"│          🍝  Restaurants → {len(restaurants)} items  ({elapsed}ms)")
        except Exception as e:
            logger.error(f"│          🍝  Restaurants → fallback  ({e})")
            restaurants = self._fallback_restaurants(destination.city)

        try:
            start = time.perf_counter()
            transport_data = gemini_adapter.generate_airport_transport(
                destination.city, airport_code, language
            )
            # Gemini sometimes returns creative mode names — normalize to train/bus/taxi
            for t in transport_data:
                t["mode"] = self._normalize_transport_mode(t.get("mode", "taxi"))
            transport_options = [TransportOption(**t) for t in transport_data]
            airport_transport = AirportTransport(
                destination="main_train_station",
                options=transport_options
            )
            elapsed = round((time.perf_counter() - start) * 1000)
            logger.info(f"│          🚇  Transport  → {len(transport_options)} modes  ({elapsed}ms)")
        except Exception as e:
            logger.error(f"│          🚇  Transport  → fallback  ({e})")
            airport_transport = self._fallback_transport()

        return DestinationContent(
            destination=destination,
            highlights=highlights,
            emergency_contacts=emergency_contacts,
            restaurants=restaurants,
            airport_transport=airport_transport
        )

    def _generate_news(self, airport_code: str, language: str) -> List[LocalNews]:
        """Generate news with Gemini directly in the target language"""
        dest_info = csv_loader.get_destination_info(airport_code)
        if not dest_info:
            raise ValueError(f"Destination not found: {airport_code}")

        city = dest_info["destination"].city

        try:
            news_data = gemini_adapter.generate_news(city, language)
            return [LocalNews(**n) for n in news_data]
        except Exception as e:
            logger.error(f"Gemini news failed: {e}")
            return []

    # ------------------------------------------------------------------
    # Fallbacks
    # ------------------------------------------------------------------

    @staticmethod
    def _fallback_highlights(city: str) -> List[Highlight]:
        return [
            Highlight(
                id=f"H00{i}",
                title=f"{city} Highlight {i}",
                brief_description=f"Discover a must-see spot in {city}.",
                long_description=f"One of the most popular places to visit in {city}. "
                                 "Ask your cabin crew for details."
            )
            for i in range(1, 6)
        ]

    @staticmethod
    def _fallback_restaurants(city: str) -> List[Restaurant]:
        cuisines = ["Local", "Mediterranean", "International"]
        return [
            Restaurant(
                name=f"{city} Restaurant {i}",
                cuisine=cuisines[i - 1],
                brief_description=f"Popular {cuisines[i - 1].lower()} restaurant in {city}.",
                long_description=f"Enjoy authentic {cuisines[i - 1].lower()} cuisine in {city}."
            )
            for i in range(1, 4)
        ]

    @staticmethod
    def _normalize_transport_mode(raw: str) -> str:
        """Map Gemini's creative mode names to valid values: train, bus, taxi."""
        raw_lower = raw.lower()
        if any(k in raw_lower for k in ("train", "tren", "metro", "rail", "line")):
            return "train"
        if any(k in raw_lower for k in ("bus", "autobús", "shuttle", "coach")):
            return "bus"
        return "taxi"

    @staticmethod
    def _fallback_weather() -> List[WeatherForecast]:
        from datetime import datetime, timedelta
        base = datetime.now()
        conditions = ["Sunny", "Partly Cloudy", "Clear"]
        return [
            WeatherForecast(
                date=(base + timedelta(days=i)).strftime("%Y-%m-%d"),
                condition=conditions[i],
                min_temperature_c=12.0 + i,
                max_temperature_c=22.0 + i
            )
            for i in range(3)
        ]

    @staticmethod
    def _fallback_transport() -> AirportTransport:
        return AirportTransport(
            destination="main_train_station",
            options=[
                TransportOption(mode="taxi", estimated_duration_minutes=30, notes="Available at arrivals exit")
            ]
        )


# Singleton instance
destination_service = DestinationService()
